package templateRules;
import com.cor.backend.model.PlayerPreferences;
import com.cor.backend.model.enums.PlayerDifficulty;

rule "qew"
    no-loop
    when
        $pp: PlayerPreferences(playerDifficulty == PlayerDifficulty.BEGINNER && playerSeriousness < 1);
    then
        $pp.getImgPaths()[0] = 'assets/positions/Bxh7$Qf5$Ng5.jpeg';
        $pp.getImgPaths()[1] = 'assets/positions/Bxh7$Qf5$Ng5.jpeg';
        $pp.getImgPaths()[2] = 'assets/positions/Bxh7$Qf5$Ng5.jpeg';
        $pp.getImgPaths()[3] = 'assets/positions/Bxh7$Qf5$Ng5.jpeg';
        update($pp);
end


