package drools.rules;

import com.cor.backend.model.Player;
import com.cor.backend.model.enums.PlayerType;
import java.util.Collections;



agenda-group "player-type"

rule "Determine player type" salience -1
    no-loop
    when
        $p: Player()
    then
        $p.setPlayerType(PlayerType.valueOf($p.getMaxCount()));
        update($p);
end

rule "Increment aggressive count"
    no-loop
    when
        $p: Player();
    then
        $p.setAggressiveCount(Collections.frequency($p.getChosenMoveTypes(), "AGGRESSIVE"));
        update($p);
end

rule "Increment tactical count"
    no-loop
    when
        $p: Player();
    then
        $p.setTacticalCount(Collections.frequency($p.getChosenMoveTypes(), "TACTICAL"));
        update($p);
end

rule "Increment positional count"
    no-loop
    when
        $p: Player();
    then
        $p.setPositionalCount(Collections.frequency($p.getChosenMoveTypes(), "POSITIONAL"));
        update($p);
end

rule "Increment defensive count"
    no-loop
    when
        $p: Player();
    then
        $p.setDefensiveCount(Collections.frequency($p.getChosenMoveTypes(), "DEFENSIVE"));
        update($p);
end
