INSERT INTO chess_game(id, game_type, pgn) VALUES (1, 0, '[Event \"Hoogovens Group A\"]\n[Site \"Wijk aan Zee NED\"]\n[Date \"1999.01.20\"]\n[EventDate \"1999.01.16\"]\n[Round \"4\"]\n[Result \"1-0\"]\n[White \"Garry Kasparov\"]\n[Black \"Veselin Topalov\"]\n[ECO \"B07\"]\n[WhiteElo \"2812\"]\n[BlackElo \"2700\"]\n[PlyCount \"87\"]\n\n1. e4 d6 2. d4 Nf6 3. Nc3 g6 4. Be3 Bg7 5. Qd2 c6 6. f3 b5\n7. Nge2 Nbd7 8. Bh6 Bxh6 9. Qxh6 Bb7 10. a3 e5 11. O-O-O Qe7\n12. Kb1 a6 13. Nc1 O-O-O 14. Nb3 exd4 15. Rxd4 c5 16. Rd1 Nb6\n17. g3 Kb8 18. Na5 Ba8 19. Bh3 d5 20. Qf4+ Ka7 21. Rhe1 d4\n22. Nd5 Nbxd5 23. exd5 Qd6 24. Rxd4 cxd4 25. Re7+ Kb6\n26. Qxd4+ Kxa5 27. b4+ Ka4 28. Qc3 Qxd5 29. Ra7 Bb7 30. Rxb7\nQc4 31. Qxf6 Kxa3 32. Qxa6+ Kxb4 33. c3+ Kxc3 34. Qa1+ Kd2\n35. Qb2+ Kd1 36. Bf1 Rd2 37. Rd7 Rxd7 38. Bxc4 bxc4 39. Qxh8\nRd3 40. Qa8 c3 41. Qa4+ Ke1 42. f4 f5 43. Kc1 Rd2 44. Qa7 1-0');
INSERT INTO chess_game(id, game_type, pgn) VALUES (2, 0, '[Event \"URS-chT Juniors\"]\n[Site \"Leningrad URS\"]\n[Date \"1954.08.??\"]\n[EventDate \"?\"]\n[Round \"?\"]\n[Result \"1-0\"]\n[White \"Mikhail Tal\"]\n[Black \"Janis Visockis\"]\n[ECO \"E87\"]\n[WhiteElo \"?\"]\n[BlackElo \"?\"]\n[PlyCount \"81\"]\n\n1.d4 Nf6 2.c4 g6 3.Nc3 Bg7 4.e4 d6 5.f3 O-O 6.Be3 e5 7.d5 Ne8\n8.Qd2 f5 9.O-O-O f4 10.Bf2 Nd7 11.Nge2 Nb6 12.Qd3 g5 13.Kb1\nBd7 14.Nc1 c5 15.dxc6 bxc6 16.c5 Nc8 17.cxd6 Nexd6 18.Bc5 Rf6\n19.Be2 Qc7 20.Nb3 Be8 21.Nd5 cxd5 22.Qxd5+ Nf7 23.Qxa8 Bc6\n24.Bb6 axb6 25.Rc1 Bxa8 26.Rxc7 Rc6 27.Rc1 Rxc7 28.Rxc7 Ncd6\n29.Nd2 Bf8 30.Bc4 b5 31.Be6 Kg7 32.a4 Kf6 33.Bxf7 Nxf7 34.axb5\nBb4 35.Nc4 g4 36.Ra7 gxf3 37.gxf3 Bxe4+ 38.fxe4 Ng5 39.b6 Bc5\n40.Ra6 Ne6 41.b7 1-0');

INSERT INTO chess_book(id, author_full_name, title, goodreads_link, book_type) VALUES (1, 'Aron Nimzowitsch', 'My System', 'https://www.goodreads.com/book/show/1430989.My_System', 3);
INSERT INTO chess_book(id, author_full_name, title, goodreads_link, book_type) VALUES (2, 'Yasser Seirawan', 'Winning Chess Combinations', 'https://www.goodreads.com/book/show/284407.Winning_Chess_Combinations', 1);
INSERT INTO chess_book(id, author_full_name, title, goodreads_link, book_type) VALUES (3, 'Mikhail Tal', 'The Life and Games of Mikhail Tal', 'https://www.goodreads.com/book/show/13674.The_Life_and_Games_of_Mikhail_Tal', 0);
INSERT INTO chess_book(id, author_full_name, title, goodreads_link, book_type) VALUES (4, 'Mark Dvoretsky', 'Dvoretsky''s Endgame Manual', 'https://www.goodreads.com/book/show/83341.Dvoretsky_s_Endgame_Manual', 1);
INSERT INTO chess_book(id, author_full_name, title, goodreads_link, book_type) VALUES (5, 'Lev Polugaevsky', 'The Art of Defence in Chess', 'https://www.goodreads.com/book/show/3347568-the-art-of-defence-in-chess', 2);
INSERT INTO chess_book(id, author_full_name, title, goodreads_link, book_type) VALUES (6, 'Samuel Reshevsky', 'The Art of Positional Play', 'https://www.goodreads.com/book/show/1904660.The_Art_of_Positional_Play', 3);
INSERT INTO chess_book(id, author_full_name, title, goodreads_link, book_type) VALUES (7, 'Gary Lane', 'How to Attack in Chess', 'https://www.goodreads.com/book/show/10441188-how-to-attack-in-chess', 0);
INSERT INTO chess_book(id, author_full_name, title, goodreads_link, book_type) VALUES (8, 'Mihail Marin', 'Secrets of Chess Defence', 'https://www.goodreads.com/book/show/2717136-secrets-of-chess-defence', 2);

INSERT INTO chess_opening(id, opening_name, description, opening_type) VALUES (1, 'King''s Gambit', 'The King''s Gambit is a chess opening that begins with the moves:\n1. e4 e5\n2. f4\nWhite offers a pawn to divert the black e-pawn. If Black accepts the gambit, White has two main plans. The first is to play d4 and Bxf4, regaining the gambit pawn with central domination. The alternative plan is to play Nf3 and Bc4 followed by 0-0, when the semi-open f-file allows White to barrel down onto the weakest point in Black''s position, the pawn on f7.', 0);
INSERT INTO chess_opening(id, opening_name, description, opening_type) VALUES (2, 'Giuoco Piano', 'The Giuoco Piano (Italian: \"Quiet Game\"; pronounced [d\u0292w\u0254\u02d0ko \u02c8pja\u02d0no]), also called the Italian Opening, is a chess opening beginning with the moves:\n1. e4 e5\n2. Nf3 Nc6\n3. Bc4 Bc5\nCommon alternatives to 3...Bc5 include 3...Nf6 (the Two Knights Defence) and 3...Be7 (the Hungarian Defence). Much less common are 3...d6 (the Semi-Italian Opening), 3...g6, 3...Nd4 (the Blackburne Shilling Gambit), and 3...f5 (the Rousseau Gambit).\n\n\n== History ==\nThe Giuoco Piano is one of the oldest recorded openings.', 1);
INSERT INTO chess_opening(id, opening_name, description, opening_type) VALUES (3, 'Slav Defense', 'The Slav Defense is a chess opening that begins with the moves:\n1. d4 d5\n2. c4 c6\nThe Slav is one of the primary defenses to the Queen''s Gambit. Although it was analyzed as early as 1590, it was not until the 1920s that it started to be explored extensively. Many masters of Slavic descent helped develop the theory of this opening, including Alapin, Alekhine, Bogoljubov, and Vidmar.\nThe Slav received an exhaustive test during the two Alekhine\u2013Euwe World Championship matches in 1935 and 1937.', 2);
INSERT INTO chess_opening(id, opening_name, description, opening_type) VALUES (4, 'London System', 'The London System is a chess opening that usually arises after 1.d4 and 2.Bf4 or 2.Nf3 & 3.Bf4. It is a \"system\" opening that can be used against virtually any black defense and thus comprises a smaller body of opening theory than many other openings. The London System is one of the Queen''s Pawn Game openings where White opens with 1.d4 but does not play the Queen''s Gambit. It normally results in a closed game.\nSverre Johnsen and Vlatko Kova\u010devi\u0107, in the introduction to their 2005 book Win with the London System, state:\n\nBasically the London is a set of solid lines where after 1.d4 White quickly develops his dark-squared bishop to f4 and normally bolsters his centre with [pawns on] c3 and e3 rather than expanding. Although it has the potential for a quick kingside attack, the white forces are generally flexible enough to engage in a battle anywhere on the board.', 3);
INSERT INTO chess_opening(id, opening_name, description, opening_type) VALUES (5, 'Nimzowitsch Defence', 'The Nimzowitsch Defence is a somewhat unusual chess opening characterised by the moves:\n1. e4 Nc6\nThis opening is an example of a hypermodern opening where Black invites White to occupy the centre of the board at an early stage with pawns. Black''s intent is to block or otherwise restrain White''s central pawns and, if allowed to do so by inaccurate play by White, eventually undermine the White pawn centre by well-timed pawn advances of his own or by attacking the white pieces defending the centre. World Champion Garry Kasparov and Grandmaster Raymond Keene wrote that it \"has never been fully accepted as a dependable opening. Nevertheless it is sound and offers the maverick spirit a great deal of foreign territory to explore.\"\nThe Nimzowitsch is included under code B00 in the Encyclopaedia of Chess Openings.\n\n\n== Main line: 2.d4 ==\nWhite takes the initiative in the centre.', 3);
INSERT INTO chess_opening(id, opening_name, description, opening_type) VALUES (6, 'Sicilian Defence', 'The Sicilian Defence is a chess opening that begins with the following moves:\n1. e4 c5\nThe Sicilian is the most popular and best-scoring response to White''s first move 1.e4. 1.d4 is a statistically more successful opening for White due to the high success rate of the Sicilian defence against 1.e4. New In Chess stated in its 2000 Yearbook that of the games in its database, White scored 56.1% in 296,200 games beginning 1.d4, but 54.1% in 349,855 games beginning 1.e4, mainly due to the Sicilian, which held White to a 52.3% score in 145,996 games.\n17% of all games between grandmasters, and 25% of the games in the Chess Informant database, begin with the Sicilian. Almost one quarter of all games use the Sicilian Defence.', 0);
INSERT INTO chess_opening(id, opening_name, description, opening_type) VALUES (7, 'King''s Indian Defence', 'The King''s Indian Defence is a common chess opening. It arises after the moves:\n1. d4 Nf6\n2. c4 g6\nBlack intends to follow up with 3...Bg7 and 4...d6 (the Gr\u00fcnfeld Defence arises when Black plays 3...d5 instead, and is considered a separate opening). White''s major third move options are 3.Nc3, 3.Nf3 or 3.g3, with both the King''s Indian and Gr\u00fcnfeld playable against these moves. The Encyclopaedia of Chess Openings classifies the King''s Indian Defence under the codes E60 through E99.', 1);
INSERT INTO chess_opening(id, opening_name, description, opening_type) VALUES (8, 'Nimzo-Indian Defence', 'The Nimzo-Indian Defence is a chess opening characterised by the moves:\n1. d4 Nf6\n2. c4 e6\n3. Nc3 Bb4\nOther move orders, such as 1.c4 e6 2.Nc3 Nf6 3.d4 Bb4, are also feasible. In the Encyclopaedia of Chess Openings, the Nimzo-Indian is classified as E20\u2013E59.\nThis hypermodern opening was developed by Aron Nimzowitsch who introduced it to master-level chess in the early 20th century.', 2);

